name: Testing Automation Anypoint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Caches dependencies and build outputs to improve workflow execution time.
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'    

      - name: Compiling and building Mule APP
        run: mvn clean package -DskipTests

      - name: Run Munit for unit test
        if: ${{ false }}
        run: mvn clean test

      - name: Install Anypoint CLI
        run: npm install -g anypoint-cli-v4

      # Automation using Any CLI (print account info, just for test CLI can do anything)
      - name: Print Account Information
        run: anypoint-cli-v4 account:user:describe --client_id cfb8011f24c54e8a81aecb16a95b37bc --client_secret 13FAd21fC91F49C1B6a2461399C504E2 -o json

      # encontrar el ORG ID
      - name: Cloudhub Apps list
        run: anypoint-cli-v4 runtime-mgr:application:list --environment Sandbox --organization c1ac5675-9276-48a0-a9f6-3075d2d317c8 --client_id cfb8011f24c54e8a81aecb16a95b37bc --client_secret 13FAd21fC91F49C1B6a2461399C504E2 -o json

      - name: Integration Testing ( Install BAT CLI)
        if: ${{ false }}
        run: curl -o- 'https://s3.amazonaws.com/bat-wrapper/install.sh' | bash && echo Integration Testing Complete
        
      - name: Running Integration Tests
        if: ${{ false }}
        run: bat ./src/test/resources/integration/bat.dwl

# This test is deactivated because the if is false, change it to true, if you want to run it.
      - name: Performance Testing
        if: ${{ false }}
        uses: grafana/k6-action@v0.2.0
        with:
          filename: ./src/test/resources/performance/test.js  
  
  
